// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// DO NOT EDIT, CODE GENERATED BY entc.

package githubrelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lrstanley/liam.sh/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ReleaseID applies equality check predicate on the "release_id" field. It's identical to ReleaseIDEQ.
func ReleaseID(v int64) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReleaseID), v))
	})
}

// HTMLURL applies equality check predicate on the "html_url" field. It's identical to HTMLURLEQ.
func HTMLURL(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHTMLURL), v))
	})
}

// TagName applies equality check predicate on the "tag_name" field. It's identical to TagNameEQ.
func TagName(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTagName), v))
	})
}

// TargetCommitish applies equality check predicate on the "target_commitish" field. It's identical to TargetCommitishEQ.
func TargetCommitish(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTargetCommitish), v))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Draft applies equality check predicate on the "draft" field. It's identical to DraftEQ.
func Draft(v bool) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDraft), v))
	})
}

// Prerelease applies equality check predicate on the "prerelease" field. It's identical to PrereleaseEQ.
func Prerelease(v bool) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPrerelease), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPublishedAt), v))
	})
}

// ReleaseIDEQ applies the EQ predicate on the "release_id" field.
func ReleaseIDEQ(v int64) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReleaseID), v))
	})
}

// ReleaseIDNEQ applies the NEQ predicate on the "release_id" field.
func ReleaseIDNEQ(v int64) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldReleaseID), v))
	})
}

// ReleaseIDIn applies the In predicate on the "release_id" field.
func ReleaseIDIn(vs ...int64) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldReleaseID), v...))
	})
}

// ReleaseIDNotIn applies the NotIn predicate on the "release_id" field.
func ReleaseIDNotIn(vs ...int64) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldReleaseID), v...))
	})
}

// ReleaseIDGT applies the GT predicate on the "release_id" field.
func ReleaseIDGT(v int64) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldReleaseID), v))
	})
}

// ReleaseIDGTE applies the GTE predicate on the "release_id" field.
func ReleaseIDGTE(v int64) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldReleaseID), v))
	})
}

// ReleaseIDLT applies the LT predicate on the "release_id" field.
func ReleaseIDLT(v int64) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldReleaseID), v))
	})
}

// ReleaseIDLTE applies the LTE predicate on the "release_id" field.
func ReleaseIDLTE(v int64) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldReleaseID), v))
	})
}

// HTMLURLEQ applies the EQ predicate on the "html_url" field.
func HTMLURLEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLNEQ applies the NEQ predicate on the "html_url" field.
func HTMLURLNEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLIn applies the In predicate on the "html_url" field.
func HTMLURLIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldHTMLURL), v...))
	})
}

// HTMLURLNotIn applies the NotIn predicate on the "html_url" field.
func HTMLURLNotIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldHTMLURL), v...))
	})
}

// HTMLURLGT applies the GT predicate on the "html_url" field.
func HTMLURLGT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLGTE applies the GTE predicate on the "html_url" field.
func HTMLURLGTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLLT applies the LT predicate on the "html_url" field.
func HTMLURLLT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLLTE applies the LTE predicate on the "html_url" field.
func HTMLURLLTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLContains applies the Contains predicate on the "html_url" field.
func HTMLURLContains(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLHasPrefix applies the HasPrefix predicate on the "html_url" field.
func HTMLURLHasPrefix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLHasSuffix applies the HasSuffix predicate on the "html_url" field.
func HTMLURLHasSuffix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLEqualFold applies the EqualFold predicate on the "html_url" field.
func HTMLURLEqualFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldHTMLURL), v))
	})
}

// HTMLURLContainsFold applies the ContainsFold predicate on the "html_url" field.
func HTMLURLContainsFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldHTMLURL), v))
	})
}

// TagNameEQ applies the EQ predicate on the "tag_name" field.
func TagNameEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTagName), v))
	})
}

// TagNameNEQ applies the NEQ predicate on the "tag_name" field.
func TagNameNEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTagName), v))
	})
}

// TagNameIn applies the In predicate on the "tag_name" field.
func TagNameIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTagName), v...))
	})
}

// TagNameNotIn applies the NotIn predicate on the "tag_name" field.
func TagNameNotIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTagName), v...))
	})
}

// TagNameGT applies the GT predicate on the "tag_name" field.
func TagNameGT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTagName), v))
	})
}

// TagNameGTE applies the GTE predicate on the "tag_name" field.
func TagNameGTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTagName), v))
	})
}

// TagNameLT applies the LT predicate on the "tag_name" field.
func TagNameLT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTagName), v))
	})
}

// TagNameLTE applies the LTE predicate on the "tag_name" field.
func TagNameLTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTagName), v))
	})
}

// TagNameContains applies the Contains predicate on the "tag_name" field.
func TagNameContains(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTagName), v))
	})
}

// TagNameHasPrefix applies the HasPrefix predicate on the "tag_name" field.
func TagNameHasPrefix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTagName), v))
	})
}

// TagNameHasSuffix applies the HasSuffix predicate on the "tag_name" field.
func TagNameHasSuffix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTagName), v))
	})
}

// TagNameEqualFold applies the EqualFold predicate on the "tag_name" field.
func TagNameEqualFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTagName), v))
	})
}

// TagNameContainsFold applies the ContainsFold predicate on the "tag_name" field.
func TagNameContainsFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTagName), v))
	})
}

// TargetCommitishEQ applies the EQ predicate on the "target_commitish" field.
func TargetCommitishEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishNEQ applies the NEQ predicate on the "target_commitish" field.
func TargetCommitishNEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishIn applies the In predicate on the "target_commitish" field.
func TargetCommitishIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTargetCommitish), v...))
	})
}

// TargetCommitishNotIn applies the NotIn predicate on the "target_commitish" field.
func TargetCommitishNotIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTargetCommitish), v...))
	})
}

// TargetCommitishGT applies the GT predicate on the "target_commitish" field.
func TargetCommitishGT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishGTE applies the GTE predicate on the "target_commitish" field.
func TargetCommitishGTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishLT applies the LT predicate on the "target_commitish" field.
func TargetCommitishLT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishLTE applies the LTE predicate on the "target_commitish" field.
func TargetCommitishLTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishContains applies the Contains predicate on the "target_commitish" field.
func TargetCommitishContains(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishHasPrefix applies the HasPrefix predicate on the "target_commitish" field.
func TargetCommitishHasPrefix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishHasSuffix applies the HasSuffix predicate on the "target_commitish" field.
func TargetCommitishHasSuffix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishEqualFold applies the EqualFold predicate on the "target_commitish" field.
func TargetCommitishEqualFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTargetCommitish), v))
	})
}

// TargetCommitishContainsFold applies the ContainsFold predicate on the "target_commitish" field.
func TargetCommitishContainsFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTargetCommitish), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldName)))
	})
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldName)))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// DraftEQ applies the EQ predicate on the "draft" field.
func DraftEQ(v bool) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDraft), v))
	})
}

// DraftNEQ applies the NEQ predicate on the "draft" field.
func DraftNEQ(v bool) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDraft), v))
	})
}

// PrereleaseEQ applies the EQ predicate on the "prerelease" field.
func PrereleaseEQ(v bool) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPrerelease), v))
	})
}

// PrereleaseNEQ applies the NEQ predicate on the "prerelease" field.
func PrereleaseNEQ(v bool) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPrerelease), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPublishedAt), v))
	})
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPublishedAt), v))
	})
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPublishedAt), v...))
	})
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.GithubRelease {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPublishedAt), v...))
	})
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPublishedAt), v))
	})
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPublishedAt), v))
	})
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPublishedAt), v))
	})
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPublishedAt), v))
	})
}

// HasRepository applies the HasEdge predicate on the "repository" edge.
func HasRepository() predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RepositoryTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepositoryTable, RepositoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepositoryWith applies the HasEdge predicate on the "repository" edge with a given conditions (other predicates).
func HasRepositoryWith(preds ...predicate.GithubRepository) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RepositoryInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepositoryTable, RepositoryColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssets applies the HasEdge predicate on the "assets" edge.
func HasAssets() predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AssetsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssetsTable, AssetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetsWith applies the HasEdge predicate on the "assets" edge with a given conditions (other predicates).
func HasAssetsWith(preds ...predicate.GithubAsset) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AssetsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssetsTable, AssetsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GithubRelease) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GithubRelease) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GithubRelease) predicate.GithubRelease {
	return predicate.GithubRelease(func(s *sql.Selector) {
		p(s.Not())
	})
}
