# syntax = docker/dockerfile:1.4

FROM ubuntu:latest

RUN \
    --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install --assume-yes \
    curl sudo \
    && rm -rf /var/lib/apt/lists/*


ENV GOROOT=/usr/local/src/go
RUN curl https://raw.githubusercontent.com/canha/golang-tools-install-script/master/goinstall.sh | bash
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

ENV NVM_DIR=/usr/local/nvm
RUN \
    --mount=type=cache,target=/usr/local/nvm/.cache \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash \
    && . /usr/local/nvm/nvm.sh && nvm install --lts -b --default

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/go/bin:${GOROOT}/bin

EXPOSE 8080
EXPOSE 8081
WORKDIR /build
