version: "3"

dotenv: [".env"]
output: prefixed

env:
  BINARY: liam.sh

tasks:
  default: "task --list-all"
  prepare:
    run: when_changed
    deps: [fetch]
    cmds:
      - go generate -x ./...
      - mkdir -vp public/dist
      - touch public/dist/.gitkeep
  fetch:
    run: always
    cmds:
      - go mod download
      - go mod tidy
  upgrade-deps: go get -u ./...
  upgrade-deps-patch: go get -u=patch ./...
  frontend-watch:
    run: always
    cmds:
      - echo test
      - while true;do echo "frontend"; sleep 10;done
  build:
    deps: [prepare]
    cmds:
      - |
        CGO_ENABLED=0 go build -ldflags '-d -s -w -extldflags=-static' \
          -tags=netgo,osusergo,static_build,go_json,nomsgpack \
          -installsuffix netgo -buildvcs=false -trimpath -o "${BINARY}"
  dlv:
    run: always
    interactive: true
    deps: [fetch]
    cmds:
      - dlv debug --headless --listen=:2345 --api-version=2 --log --allow-non-terminal-interactive -- --debug
  debug:
    run: always
    method: none
    ignore_error: true
    deps: [prepare]
    cmds:
      - while kill $(pgrep http 2>/dev/null) 2>/dev/null;do sleep 1;done
      - go run *.go --debug
    sources:
      - "**/*.go"
    generates:
      - "**/*.go"
