query base {
    self {
        id
        name
        login
        avatarURL
    }

    githubUser {
        login
        name
        avatarURL
        bio
        email
        location
        htmlurl
    }

    version {
        commit
        goVersion
        date
    }
}

query getPostContent($slug: String!) {
    posts(where: { slugEqualFold: $slug }) {
        edges {
            node {
                id
                title
                slug
                contentHTML
                author {
                    name
                    login
                    avatarURL
                    htmlURL
                }
                labels {
                    edges {
                        node {
                            id
                            name
                        }
                    }
                }
                publishedAt
            }
        }
    }
}

query getPosts(
    $count: Int = 25
    $cursor: Cursor
    $order: OrderDirection = DESC
    $orderBy: PostOrderField = DATE
) {
    posts(first: $count, after: $cursor, orderBy: { direction: $order, field: $orderBy }) {
        edges {
            node {
                id
                title
                slug
                publishedAt
                labels {
                    edges {
                        node {
                            id
                            name
                        }
                    }
                }
                author {
                    login
                    avatarURL
                }
            }
        }
        pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
    }
}

query getLabels {
    labels(first: 100, orderBy: { direction: ASC, field: NAME }) {
        edges {
            node {
                id
                name
            }
        }
    }
}
