version: "3"
services:
  devimage:
    image: devimage
    env_file: ../.env
    tty: true
    build:
      context: ../
      dockerfile: Dockerfile.dev
  # frontend:
  #   image: devimage
  #   env_file: ../.env
  #   user: $USER:$GROUP
  #   ports: [ 8081:8081 ]
  #   working_dir: /build/public
  #   volumes:
  #     - /etc/passwd:/etc/passwd:ro
  #     - /etc/group:/etc/group:ro
  #     - ../:/build/ # root of repository
  http-server:
    image: devimage
    depends_on: [postgres]
    env_file: ../.env
    # user: $USER:$GROUP
    ports: [8080:8080]
    working_dir: /build
    command: task --parallel --watch frontend-watch debug
    environment:
      - HOME=/src
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../:/build/ # root of repository
      - /src/.cache/go-build
      - /src/go/pkg/mod
  postgres:
    image: postgres
    env_file: ../.env
    ports: [5432:5432]
    environment:
      - PGDATA=/database
