// Code generated by ogen, DO NOT EDIT.

package ogent

type DeleteUserParams struct {
	// ID of the User.
	ID int
}

type ListUserParams struct {
	// What page to render.
	Page OptInt
	// Item count to render per page.
	ItemsPerPage OptInt
}

type ReadUserParams struct {
	// ID of the User.
	ID int
}

type UpdateUserParams struct {
	// ID of the User.
	ID int
}
