// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"github.com/go-faster/jx"
	"go.opentelemetry.io/otel/trace"
)

func encodeCreateUserRequestJSON(req CreateUserReq, span trace.Span) (data *jx.Encoder, err error) {
	e := jx.GetEncoder()

	req.Encode(e)

	return e, nil
}

func encodeUpdateUserRequestJSON(req UpdateUserReq, span trace.Span) (data *jx.Encoder, err error) {
	e := jx.GetEncoder()

	req.Encode(e)

	return e, nil
}
