name: test

on:
  pull_request:
    branches: [master, main]
    paths-ignore: [".gitignore", "**/*.md"]
  push:
    branches: [master, main]
    paths-ignore: [".gitignore", "**/*.md"]

jobs:
  test:
    uses: lrstanley/.github/.github/workflows/lang-go-test-matrix.yml@master
    with: { num-minor: 2, num-patch: 2 }
  lint:
    uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
