name: triage

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  triage:
    uses: lrstanley/.github/.github/workflows/triage.yml@master
    secrets:
      token: ${{ secrets.USER_PAT }}
